### ISSUE TITLE
Group x-dash upgrades into a single pull request

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/renovate-config-next#19]
The x-dash project is a mono-repository.

When a new version is released, currently Renovate opens separate pull requests for each package that x-dash publishes.

Realistically these package upgrades can all be released together.

Renovate supports this via group presets documented at https://renovatebot.com/docs/noise-reduction/#package-grouping.

**Comment by sjparkinson** [comment]
![image](https://user-images.githubusercontent.com/51677/51113079-bbb46200-17f8-11e9-9108-50e656c95a01.png)

> https://github.com/Financial-Times/next-video-page/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Adependencies+%22%2Fx-%22+

**Comment by quarterto** [comment]
this could be configured as

```json
  "packagePatterns": [
    "^@financial-times/x-"
  ]
```
